apiPath:
  nomp: /api/stats
timeout:
  api: 10000
  stratum: 1000
maxRetry: 4
webs:
  -
    name: みんなのプール
    url: https://www.minnano-pool.work
    restarTarget: true
    pm2id: 1
    pools:
      -
        coin: bitzeny
        threshold: 1000
        pm2id: 1
      -
        coin: bitzeny
        pm2id: 2
      -
        coin: monacoin
        pm2id: 3
stratums:
  -
    name: みんなのプール(bitzeny)
    host: localhost
    port: 3031
    pm2id: 1
  -
    name: みんなのプール(koto)
    host: localhost
    port: 3131
    pm2id: 2
  -
    name: みんなのプール(monacoin)
    host: localhost
    port: 3231
    pm2id: 3
